// Florida Department of Revenue county codes (CO_NO), used by the statewide
// cadastral service (see app/api/parcel-lookup/route.ts's FL_CONFIG and
// lib/leadGenerator.ts). Standard alphabetical DOR numbering, 11-77.
export const FL_COUNTIES: { name: string; coNo: number }[] = [
  { name: "Alachua", coNo: 11 },
  { name: "Baker", coNo: 12 },
  { name: "Bay", coNo: 13 },
  { name: "Bradford", coNo: 14 },
  { name: "Brevard", coNo: 15 },
  { name: "Broward", coNo: 16 },
  { name: "Calhoun", coNo: 17 },
  { name: "Charlotte", coNo: 18 },
  { name: "Citrus", coNo: 19 },
  { name: "Clay", coNo: 20 },
  { name: "Collier", coNo: 21 },
  { name: "Columbia", coNo: 22 },
  { name: "Miami-Dade", coNo: 23 },
  { name: "DeSoto", coNo: 24 },
  { name: "Dixie", coNo: 25 },
  { name: "Duval", coNo: 26 },
  { name: "Escambia", coNo: 27 },
  { name: "Flagler", coNo: 28 },
  { name: "Franklin", coNo: 29 },
  { name: "Gadsden", coNo: 30 },
  { name: "Gilchrist", coNo: 31 },
  { name: "Glades", coNo: 32 },
  { name: "Gulf", coNo: 33 },
  { name: "Hamilton", coNo: 34 },
  { name: "Hardee", coNo: 35 },
  { name: "Hendry", coNo: 36 },
  { name: "Hernando", coNo: 37 },
  { name: "Highlands", coNo: 38 },
  { name: "Hillsborough", coNo: 39 },
  { name: "Holmes", coNo: 40 },
  { name: "Indian River", coNo: 41 },
  { name: "Jackson", coNo: 42 },
  { name: "Jefferson", coNo: 43 },
  { name: "Lafayette", coNo: 44 },
  { name: "Lake", coNo: 45 },
  { name: "Lee", coNo: 46 },
  { name: "Leon", coNo: 47 },
  { name: "Levy", coNo: 48 },
  { name: "Liberty", coNo: 49 },
  { name: "Madison", coNo: 50 },
  { name: "Manatee", coNo: 51 },
  { name: "Marion", coNo: 52 },
  { name: "Martin", coNo: 53 },
  { name: "Monroe", coNo: 54 },
  { name: "Nassau", coNo: 55 },
  { name: "Okaloosa", coNo: 56 },
  { name: "Okeechobee", coNo: 57 },
  { name: "Orange", coNo: 58 },
  { name: "Osceola", coNo: 59 },
  { name: "Palm Beach", coNo: 60 },
  { name: "Pasco", coNo: 61 },
  { name: "Pinellas", coNo: 62 },
  { name: "Polk", coNo: 63 },
  { name: "Putnam", coNo: 64 },
  { name: "St. Johns", coNo: 65 },
  { name: "St. Lucie", coNo: 66 },
  { name: "Santa Rosa", coNo: 67 },
  { name: "Sarasota", coNo: 68 },
  { name: "Seminole", coNo: 69 },
  { name: "Sumter", coNo: 70 },
  { name: "Suwannee", coNo: 71 },
  { name: "Taylor", coNo: 72 },
  { name: "Union", coNo: 73 },
  { name: "Volusia", coNo: 74 },
  { name: "Wakulla", coNo: 75 },
  { name: "Walton", coNo: 76 },
  { name: "Washington", coNo: 77 },
];

export const CO_NO_TO_COUNTY: Record<number, string> = Object.fromEntries(
  FL_COUNTIES.map((c) => [c.coNo, c.name])
);
